build_package <- function(path = ".", build_site = FALSE) {
  # Run styler on R code
  styler::style_pkg(path)
  # Recompile the rust code and generate C bindings
  savvy::savvy_update(path)
  # Remove the R wrappers generated by savvy
  file.remove(file.path(path, "R", "000-wrappers.R"))
  # Document and load the package
  devtools::document(path)
  devtools::load_all(path)
  # Build the webite
  if (build_site) {
    pkgdown::build_site()
  }
}

build_package()
