# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib distanamo, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_distanamo__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_distanamo__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


### wrapper functions for InterpolationGrid

`InterpolationGrid_get_source_grid` <- function(self) {
  function() {
    .Call(savvy_InterpolationGrid_get_source_grid__impl, `self`)
  }
}

`InterpolationGrid_get_interpolated_grid` <- function(self) {
  function() {
    .Call(savvy_InterpolationGrid_get_interpolated_grid__impl, `self`)
  }
}

`InterpolationGrid_transform_layer` <- function(self) {
  function(`background_layer`) {
    .Call(savvy_InterpolationGrid_transform_layer__impl, `self`, `background_layer`)
  }
}

`InterpolationGrid_deformation_strength` <- function(self) {
  function() {
    .Call(savvy_InterpolationGrid_deformation_strength__impl, `self`)
  }
}

`InterpolationGrid_sum_squared_deformation_strength` <- function(self) {
  function() {
    .Call(savvy_InterpolationGrid_sum_squared_deformation_strength__impl, `self`)
  }
}

`InterpolationGrid_resolution` <- function(self) {
  function() {
    .Call(savvy_InterpolationGrid_resolution__impl, `self`)
  }
}

`InterpolationGrid_bbox` <- function(self) {
  function() {
    .Call(savvy_InterpolationGrid_bbox__impl, `self`)
  }
}

`.savvy_wrap_InterpolationGrid` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`get_source_grid` <- `InterpolationGrid_get_source_grid`(ptr)
  e$`get_interpolated_grid` <- `InterpolationGrid_get_interpolated_grid`(ptr)
  e$`transform_layer` <- `InterpolationGrid_transform_layer`(ptr)
  e$`deformation_strength` <- `InterpolationGrid_deformation_strength`(ptr)
  e$`sum_squared_deformation_strength` <- `InterpolationGrid_sum_squared_deformation_strength`(ptr)
  e$`resolution` <- `InterpolationGrid_resolution`(ptr)
  e$`bbox` <- `InterpolationGrid_bbox`(ptr)

  class(e) <- c("InterpolationGrid", "savvy_distanamo__sealed")
  e
}



`InterpolationGrid` <- new.env(parent = emptyenv())

### associated functions for InterpolationGrid

`InterpolationGrid`$`new` <- function(`source_points`, `image_points`, `precision`, `n_iter`, `bbox`) {
  .savvy_wrap_InterpolationGrid(.Call(savvy_InterpolationGrid_new__impl, `source_points`, `image_points`, `precision`, `n_iter`, `bbox`))
}


class(`InterpolationGrid`) <- c("InterpolationGrid__bundle", "savvy_distanamo__sealed")

#' @export
`print.InterpolationGrid__bundle` <- function(x, ...) {
  cat('InterpolationGrid')
}

